name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '19,39,59 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        curl 'https://powercuts.nationalgrid.co.uk/__powercuts/getIncidentsAndAlertSummary' | jq > incidents-and-alerts-summary.json
    - name: Commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
